# Generated by Django 5.0.7 on 2024-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_color_size_alter_review_rating_item_color_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(null=True, to='store.color'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(null=True, to='store.size'),
        ),
    ]
