# Generated by Django 5.0.7 on 2024-08-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_item_color_remove_item_size_item_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='store.color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='store.size'),
        ),
    ]
