# Generated by Django 5.0.7 on 2024-08-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_item_color_alter_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(blank=True, to='store.color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(blank=True, to='store.size'),
        ),
    ]
