# Generated by Django 5.0.7 on 2024-08-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_item_information_alter_item_color_alter_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
