# Generated by Django 5.0.7 on 2024-08-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
