# Generated by Django 5.0.7 on 2024-09-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_cart_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
