# Generated by Django 5.0.7 on 2024-09-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_shippinginfo_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cart'),
        ),
    ]
