# Generated by Django 5.0.7 on 2024-09-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_shippinginfo_cart_cart_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='store.shippinginfo'),
        ),
    ]
