# Generated by Django 5.0.7 on 2024-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_rename_address_line_1_shippinginfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
