# Generated by Django 5.0.7 on 2024-10-26 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_cart_user_alter_shippinginfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cart'),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
