# Generated by Django 5.0.7 on 2024-10-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_remove_cart_shipping_address_shippinginfo_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
